{"name": "test_estimate_bridge_not_native_to_native[Ethereum (ETH)]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"No available RPC's for ETH\"}.", "trace": "network = 'Ethereum (ETH)'\n\n    @pytest.mark.parametrize(\"network\", networks)\n    def test_estimate_bridge_not_native_to_native(network):\n        net = de_bridge_keys_data()[network].get('net')\n        native_token = de_bridge_keys_data()[network].get('nativeToken')\n        not_native_token = de_bridge_keys_data()[network].get('notNativeToken')\n>       DeBridge().EstimateBridge().estimate_bridge_not_native_to_native(net=net, native_token=native_token,\n                                                                         not_native_token=not_native_token)\n\ntests/api_tests/tests_de_bridge.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge.EstimateBridge object at 0x10eadca90>\nnet = 'eth', not_native_token = '0x2a3bff78b79a009976eea096a51a948a3dc00e34'\nnative_token = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'\n\n    def estimate_bridge_not_native_to_native(self, net, not_native_token, native_token):\n        response = requests.get(\n            f\"{self.url}?srcNet={net}&srcTokenAddress={not_native_token}\"\n            f\"&srcTokenAmount=1&dstNet={net}&dstTokenAddress={native_token}\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"No available RPC's for ETH\"}.\n\nserviceCalls/debrdige_service.py:65: AssertionError"}, "attachments": [{"name": "log", "source": "66c26f5a-6590-4207-a23d-b31cd15fb5f4-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "network", "value": "'Ethereum (ETH)'"}], "start": 1685610399788, "stop": 1685610400189, "uuid": "16271abb-8e51-4c27-b893-a208511b39a1", "historyId": "9dba76cd4ff5a5b91d85ada15b7475a6", "testCaseId": "f166ccaf1cb63e9625a89429066bdc6d", "fullName": "tests.api_tests.tests_de_bridge#test_estimate_bridge_not_native_to_native", "labels": [{"name": "parentSuite", "value": "tests.api_tests"}, {"name": "suite", "value": "tests_de_bridge"}, {"name": "host", "value": "MacBook-Air-Anna.local"}, {"name": "thread", "value": "16727-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.tests_de_bridge"}]}